import Nav from '@/components/layout/Nav/Nav';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio 2023</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Nav />
    </>
  );
}
